spring.application.name=c03-subscriber
server.port=8081

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASS:admin}

mpi.hosts=${MPI_HOSTS:localhost}
mpi.np=2

c05.rest.url=${C05_REST_URL:http://localhost:3000}
